# Site settings
title: sdb's wiki
description: >- # this means to ignore newlines until "baseurl:"
  Sagrys de Beer's personal wiki for stuff
author: Sagrys de Beer
keywords: blog,wiki,programming
repository: sagrysdebeer/sagrysdebeer.github.io

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
